# Generated by Django 4.0.3 on 2022-04-09 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglink',
            old_name='podcast_name',
            new_name='publication_name',
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.bloglink'),
        ),
    ]
