# Generated by Django 4.0.3 on 2022-04-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0003_alter_article_publication_name_alter_article_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
